pipeline {
    agent {
        docker {
            image 'python:3.12'
            registryCredentialsId 'docker-cred'
            args '--entrypoint="" -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker --group-add 110'
        }
    }

    environment {
        DOCKER_IMAGE = "adilbinanwar/test-django-app"
        SONAR_URL = "http://13.127.102.252:9000/"
    }

    stages {

        stage('Checkout') {
            steps {
                sh 'echo Repository checked out'
            }
        }

        stage('Debug Workspace') {
            steps {
                sh '''
                pwd
                echo "===== ROOT ====="
                ls -la
                echo "===== ALL FILES ====="
                find . -type f | sort
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r django_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest --cov=. --cov-report=xml
                '''
            }
        }

        stage('SonarQube Analysis') {
            steps {
        
                script {
                    def scannerHome = tool 'SonarScanner'
                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=test_django_project \
                        -Dsonar.sources=django_app \
                        -Dsonar.host.url=$SONAR_HOST_URL \
                        -Dsonar.token=$SONAR_AUTH_TOKEN
                        """
                    }
                }
        
            }
        }

        stage('Build Docker Image') {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-cred',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                    docker build \
                    -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ./django_app

                    docker push \
                    ${DOCKER_IMAGE}:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Update Deployment File') {
            environment {
                GIT_REPO_NAME = "test_django_project"
                GIT_USER_NAME = "adilbinanwar"
                HOME = "${env.WORKSPACE}"
            }
        
            steps {
                withCredentials([
                    string(credentialsId: 'github',
                    variable: 'GITHUB_TOKEN')
                ]) {
        
                    sh '''
                    git config --global --add safe.directory ${WORKSPACE}
                    git config user.email "adil004anwar@gmail.com"
                    git config user.name "adilbinanwar"
                    git checkout main
                    git pull https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} main
                    sed -i "s|image: adilbinanwar/test-django-app:.*|image: adilbinanwar/test-django-app:${BUILD_NUMBER}|g" django_app_manifests/deployment.yml
                    git add django_app_manifests/deployment.yml
                    git commit -m "Update Django image version ${BUILD_NUMBER}" || true
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                    '''
                }
            }
        }
        
    }
}
