apiVersion: apps/v1
kind: Deployment

metadata:
  name: django-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: django-app

  template:
    metadata:
      labels:
        app: django-app

    spec:
      containers:
      - name: django-app

        image: adilbinanwar/test-django-app:16

        ports:
        - containerPort: 8000